// public/sw.js
const CACHE_NAME = `pwa-cache-001`;
const OFFLINE_PAGE = "/offline.html";

// Assets to cache on install
const PRECACHE_ASSETS = [
  // Core HTML files (actual paths in dist/)
  "/index.html",
  "/about/index.html",
  "/contact/index.html",
  "/projects/index.html",
  "/services/index.html",
  "/team/index.html",
  "/offline.html",

  // Static assets (in public/)
  "/file.svg",
  "/globe.svg",
  "/vercel.svg",
  "/window.svg",
  "/resume.pdf",

  // Icons & images
  "/images/meta/favicon-16x16.png",
  "/images/meta/favicon-32x32.png",
  "/images/meta/apple-touch-icon.png",
  "/images/meta/android-chrome-192x192.png",
  "/images/meta/android-chrome-512x512.png",
  "/images/meta/mstile-70x70.png",
  "/images/meta/mstile-150x150.png",
  "/images/meta/mstile-310x150.png",
  "/images/meta/mstile-310x310.png",
  "/images/meta/og-image.jpg",

  "/images/profile/profile.webp",
  "/images/team/member-1.webp",
  "/images/team/member-2.webp",
  "/images/team/member-3.webp",
  "/images/team/member-4.webp",

  "/images/projects/irs-calculator/1.webp",
  "/images/projects/irs-calculator/2.webp",
  "/images/projects/irs-calculator/3.webp",
  "/images/projects/wkdkavishka-vue/1.webp",
  "/images/projects/wkdkavishka-vue/2.webp",
  "/images/projects/wkdkavishka-vue/3.webp",
  "/images/projects/wkdkavishka-vue/4.webp",

  "/images/pwa/desktop-1.png",
  "/images/pwa/desktop.png",
  "/images/pwa/mobile.png",

  // PWA manifest (generated by Next.js)
  "/manifest.json",
];

// Helper: Fetch and cache one-by-one (ignores 404s or failures)
async function safeCacheAddAll(cache, urls) {
  for (const url of urls) {
    try {
      const response = await fetch(url, { credentials: "omit" });
      if (response.ok) {
        await cache.put(url, response);
        console.log(`[SW] Cached: ${url}`);
      } else {
        console.warn(`[SW] Skip (not found): ${url} → ${response.status}`);
      }
    } catch (err) {
      console.warn(`[SW] Skip (failed): ${url}`, err);
    }
  }
}

// INSTALL: Precache safely
self.addEventListener("install", (event) => {
  console.log("[SW] Installing...");
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      return safeCacheAddAll(cache, PRECACHE_ASSETS);
    }).then(() => self.skipWaiting())
  );
});

// ACTIVATE: Clean up old caches
self.addEventListener("activate", (event) => {
  console.log("[SW] Activating...");
  event.waitUntil(
    caches.keys().then((cacheNames) => {
      return Promise.all(
        cacheNames
          .filter((name) => name !== CACHE_NAME)
          .map((name) => {
            console.log(`[SW] Deleting old cache: ${name}`);
            return caches.delete(name);
          })
      );
    }).then(() => self.clients.claim())
  );
});

// FETCH: Network-first, fallback to cache, then offline page
self.addEventListener("fetch", (event) => {
  const { request } = event;

  // Skip non-GET and chrome-extension
  if (
    request.method !== "GET" ||
    request.url.startsWith("chrome-extension://")
  ) {
    return;
  }

  event.respondWith(
    fetch(request)
      .then((response) => {
        // Cache successful responses (except HTML for now)
        if (response && response.status === 200) {
          const responseClone = response.clone();
          caches.open(CACHE_NAME).then((cache) => {
            cache.put(request, responseClone);
          });
        }
        return response;
      })
      .catch(() => {
        return caches.match(request).then((cached) => {
          return cached || caches.match(OFFLINE_PAGE);
        });
      })
  );
});

// Optional: Skip waiting on message (for RegisterSW.tsx)
self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") {
    self.skipWaiting();
  }
});